default_language_version:
  python: python3.10.2
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-ast
      - id: requirements-txt-fixer
      - id: check-case-conflict
      - id: check-docstring-first
      - id: fix-encoding-pragma
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        args: ["--profile", "black"]
        name: isort-black-profile (python3)
